version: '3.8'

services:
  jellyfin-audit:
    build: .
    image: jellyfin-audit:latest
    container_name: jellyfin-audit-app
    restart: unless-stopped
    ports:
      - "8098:8098"
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  volumes:
    -  /home/docker/jellyfin-audit/data:/app/data
  
      